# Generated by Django 4.2.2 on 2023-06-06 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='insEstadual',
            new_name='inscEstadual',
        ),
    ]
